name: firebase_auth_services
description: In this application, you can use Firebase Authentication for user registration, login, email update, and logout functionalities, while managing the user token locally using Shared Preferences.

version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  firebase_auth: ^3.4.0
  firebase_core: ^1.24.0
  shared_preferences: ^2.3.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

license: MIT